# Generated by Django 3.2 on 2022-12-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('isActive', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='product/default.webp', null=True, upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='brand/default.webp', null=True, upload_to='brand/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='product/default.webp', null=True, upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLubricant',
            fields=[
                ('abstractproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.abstractproduct')),
                ('volume', models.CharField(blank=True, choices=[('barrel', 'barrel'), ('kanister', 'kanister'), ('other', 'other')], max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.ImageField(blank=True, default='thumbnail/default.webp', null=True, upload_to='thumbnail/')),
            ],
            bases=('catalog.abstractproduct',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.image')),
            ],
        ),
        migrations.AddField(
            model_name='abstractproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='abstractproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category'),
        ),
    ]
