# Generated by Django 3.2 on 2022-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221210_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractproduct',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
