# Generated by Django 3.2 on 2022-12-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221209_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractproduct',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='category/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
