# Generated by Django 3.2 on 2022-09-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220922_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_1',
            new_name='image',
        ),
    ]
