# Generated by Django 3.2 on 2022-09-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_image_1_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='media/picture_create/free_tar.png', null=True, upload_to='thumbnail/'),
        ),
    ]
